services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LeadingSystems\LSJS4CBundle\EventSubscriber\LsjsInsertionSubscriber:
    arguments:
      - '@contao.framework'
      - '@contao.routing.scope_matcher'
      - '%contao.web_dir%'
      - '%kernel.project_dir%'
    tags:
      - { name: 'kernel.event_subscriber' }

  LeadingSystems\LSJS4CBundle\EventListener\GetPageLayoutListener:
    tags:
      - { name: contao.hook, hook: getPageLayout, method: getLayoutSettingsForGlobalUse }

  LeadingSystems\LSJS4CBundle\EventListener\GeneratePageListener:
    arguments:
      - '%kernel.project_dir%'
    tags:
      - { name: contao.hook, hook: generatePage, method: insertLsjs }