<?php
	/*
	 * Fields
	 */
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_loadLsjs'] = array('Load LSJS javascript main component', 'Define whether you want to load the javascript main component of LSJS. This is necessary if you want to use LSJS apps in this layout.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_appToLoad'] = array('App to load', 'Select the directory of the LSJS app you want to load.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_appToLoadTextPath'] = array('App to be loaded (free path specification)', 'If you want to specify a resource that is located outside the "files" directory of Contao, specify the path here.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_appCustomizationToLoad'] = array('App customization to load', 'Select the directory of the app customization you want to load. Please refer to the LSJS documentation for more information.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_appCustomizationToLoadTextPath'] = array('App customization to load (free path specification)', 'If you want to specify a resource that is located outside the "files" directory of Contao, specify the path here.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_coreCustomizationToLoad'] = array('Core customization to load', 'Select the directory of the core customization you want to load. Please refer to the LSJS documentation for more information.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_coreCustomizationToLoadTextPath'] = array('Core customization to be loaded (free path specification)', 'If you want to specify a resource that is located outside the "files" directory of Contao, specify the path here.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_debugMode'] = array('Debug mode', 'In this mode, template paths will be displayed in the html output rendered by LSJS.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_noMinifier'] = array('Don\'t use minifier', 'Don\'t optimize and reduce the size of output generated by LSJS');

	/*
	 * Legends
	 */
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_legend']   = 'LSJS';
?>
