<?php
	/*
	 * Fields
	 */
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_loadLsjs'] = array('Load LSJS javascript main component', 'Define whether you want to load the javascript main component of LSJS. This is necessary if you want to use LSJS apps in this layout.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_appsToLoad'] = array('Apps to be loaded & app customizations', 'Select the directories of the LSJS apps that you want to load. All possible LSJS apps available in the system are displayed here.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_coreCustomizationsToLoad'] = array('Core customizations to be loaded', 'Select the directories of the core customizations that you want to load. All possible core customizations available in the system are displayed here.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_debugMode'] = array('Debug mode', 'In this mode, template paths will be displayed in the html output rendered by LSJS.');
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_noMinifier'] = array('Don\'t use minifier', 'Don\'t optimize and reduce the size of output generated by LSJS');

	/*
	 * Legends
	 */
	$GLOBALS['TL_LANG']['tl_layout']['lsjs4c_legend']   = 'LSJS';
?>
